## ---- Required libraries
library(tidyverse)
library(data.table)
library(tibble)
library(runner)
library(lubridate)

library(sf)
library(sp)
library(rgdal)
library(raster)
library(rasterVis)
library(gstat)
library(tmap)

library(HeatStress)
library(weathermetrics)
library(NicheMapR)

library(skimr)
library(viridis)

library(RPostgreSQL)
library(readr)
library(pool)
library(fst)
library(naniar)
library(feather)
library(readxl)
library(furrr)
library(corrr)
library(glue)
